Restart function, need_root, CONFDIR if chrooted, misc messages

diff --git a/iroffer.init b/iroffer.init
--- a/iroffer.init
+++ b/iroffer.init
@@ -17,6 +17,7 @@ PIDDIR=$DIRNAME/pid
 if [[ $CHROOT = "true" ]]; then
   ARGS="$ARGS -t $CHROOT_DIR -u $CHROOT_USER $CHROOT_CONFDIR"
   USER=root
+  CONFDIR="${CHROOT_DIR}${CHROOT_CONFDIR}"
 else
   ARGS="$ARGS $CONFDIR"
 fi
@@ -32,11 +33,19 @@ if [ ! -e "$PIDDIR" ];then
        fi
 fi
 
+need_root(){
+ if [ $UID -ne 0 ]; then
+  log_failure_msg "Operation need root rights"
+  exit 1
+ fi
+}
+
 genconf_iroffer(){
   BOTNAME=$1
   if [ -f $METACONFDIR/$BOTNAME.py ]; then
-    log_daemon_msg "  Generating config for $BOTNAME"
+    log_daemon_msg "Generating config for $BOTNAME"
     $METACONFDIR/$BOTNAME.py > $CONFDIR/$BOTNAME.config
+    log_end_msg $?
   else
     log_failure_msg " File $DIRNAME/$BOTNAME.py missing"
   fi
@@ -44,57 +53,57 @@ genconf_iroffer(){
 
 start_iroffer(){
   BOTNAME=$1
+  need_root
   # see if stale pid file
   if [ -f $PIDDIR/${BOTNAME}.pid ]; then
     pid=`cat $PIDDIR/${BOTNAME}.pid`
     if [ `ps -p $pid | wc -l` -eq 2 ]; then
-      log_failure_msg "  $BOTNAME already running"
+      log_failure_msg "$BOTNAME already running"
       return
     else
-      log_warning_msg "  Stale PID File for $BOTNAME"
+      log_warning_msg "Stale PID File for $BOTNAME"
     fi
   fi
 
-  log_daemon_msg "  Starting iroffer $BOTNAME..."
+  log_daemon_msg "Starting iroffer $BOTNAME..."
   /bin/su -l $USER -c "$DAEMON $ARGS/$BOTNAME.config"
 }
 
 stop_iroffer(){
   BOTNAME=$1
+  need_root
   if [ -f $PIDDIR/${BOTNAME}.pid ]; then
     pid=`cat $PIDDIR/${BOTNAME}.pid`
-    echo -n "  Stopping $NAME $BOTNAME"
+    echo -n " * Stopping $NAME $BOTNAME"
     for i in `seq 30`; do
       echo -n "."
       if [ `ps -p $pid | wc -l` -eq 2 ]; then
         kill $pid
       else
-        echo OK
+        log_end_msg 0
         return
       fi
       sleep 1
     done
-    echo FAILED
+    log_end_msg 1
   else
-    log_warning_msg "  $PIDDIR/${BOTNAME}.pid no found"
+    log_warning_msg "$PIDDIR/${BOTNAME}.pid no found"
   fi
 }
 
 reload_iroffer(){
   BOTNAME=$1
+  need_root
   if [ -f $PIDDIR/${BOTNAME}.pid ]; then
     pid=`cat $PIDDIR/${BOTNAME}.pid`
-    log_daemon_msg "  Reloading config of $BOTNAME"
+    log_daemon_msg "Reloading config of $BOTNAME"
     kill -n 12 $pid
   else
-    log_failure_msg "  $PIDDIR/${BOTNAME}.pid no found"
+    log_failure_msg "$PIDDIR/${BOTNAME}.pid no found"
   fi
 }
 
 start(){
-    log_daemon_msg "Starting $DESC" "$NAME"
-    cd $DIRNAME
-
     # make sure filesystem isn't full
     freespace=`df -k . | tail -1 | awk {'print $4'}`
     if [ $freespace -lt 10 ]; then
@@ -119,7 +128,6 @@ start(){
     fi
 }
 stop(){
-    log_daemon_msg "Stopping $DESC" "$NAME"
     if test -z "$2" ; then
       for BOT in `cd $CONFDIR; ls *.config 2> /dev/null`; do
         BOTNAME=${BOT%%.config}
@@ -131,6 +139,32 @@ stop(){
         BOTNAME=$1
         if test -e $CONFDIR/$BOTNAME.config ; then
             stop_iroffer $BOTNAME
+        else
+          log_failure_msg "$BOTNAME, missing $CONFDIR/$BOTNAME.config"
+        fi
+      done
+    fi
+}
+restart(){
+    # make sure filesystem isn't full
+    freespace=`df -k . | tail -1 | awk {'print $4'}`
+    if [ $freespace -lt 10 ]; then
+      log_failure_msg "Filesystem Full!"
+      exit
+    fi
+    if test -z "$2" ; then
+      for BOT in `cd $CONFDIR; ls *.config 2> /dev/null`; do
+        BOTNAME=${BOT%%.config}
+        stop_iroffer $BOTNAME
+        start_iroffer $BOTNAME
+      done
+    else
+      while shift ; do
+        [ -z "$1" ] && break
+        BOTNAME=$1
+        if test -e $CONFDIR/$BOTNAME.config ; then
+            stop_iroffer $BOTNAME
+            start_iroffer $BOTNAME
         else
           log_failure_msg "$BOTNAME, missing $CONFDIR/$BOTNAME.config"
         fi
@@ -174,8 +208,7 @@ case $1 in
     stop $@
   ;;
   restart)
-    stop $@
-    start $@
+    restart $@
   ;;
   reload)
     log_daemon_msg "Reloading $DESC" "$NAME"
